
services:
  - type: worker
    name: tg-news-bot
    env: python
    autoDeploy: true
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.bot
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: CHECK_INTERVAL
        value: "1200"
      - key: DB_PATH
        value: /data/state.db
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
